### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by KnightRider37** [evjrob/bayes-bet#17]
There is an error on the website:
Server Error (500)

**Comment by jmp2626** [comment]
NHL updated their API

**Comment by evjrob** [comment]
Yeah, the NHL API this relies on has changed. I I’ll see if I can figure out the new one this weekend.

**Comment by KnightRider37** [comment]
Thanks ! 
Found this while I was looking around for a solution. Maybe it could help:
https://github.com/Zmalski/NHL-API-Reference

**Comment by evjrob** [comment]
Hey, sorry it took so long to get this sorted out.  My original deployment setup was pretty broken after so much time since I last worked on it and getting that all fixed took some extra effort. I took that as an opportunity to migrate the project to a new dedicated URL as well: bayesbet.io

**Comment by evjrob** [comment]
I'll setup the original bayesbet.everettsprojects.com domain to redirect to this new one.
